<a href="https://colab.research.google.com/github/Hemanth-nri/Numpy/blob/main/Introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr =np.array([[1,2,3],[4,5,6]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr1 = np.random.randint(1,2,(3,1))

In [ ]:
arr.shape
arr1.shape

(3, 1)

In [ ]:
result = np.dot(arr,arr1)

In [ ]:
print (result)

[[ 6]
 [15]]


In [ ]:
r1 =np.random.randint(10,20,(3,3))

In [ ]:
print (r1)

[[15 11 19]
 [14 18 15]
 [18 19 12]]


In [ ]:
r2 = np.eye(3)
print (r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
result2 = np.eye(3)
print (result2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
t1 = np.random.randint(3,6,(3,3))
t2 = np.random.randint(3,6,(3,3))

In [ ]:
print (t1)
print (t2)

[[4 5 3]
 [5 3 3]
 [5 4 4]]
[[4 3 5]
 [3 3 5]
 [5 4 4]]


In [ ]:
t3 = (t1) + (t2)

In [ ]:
print (t3)

[[ 8  8  8]
 [ 8  6  8]
 [10  8  8]]


In [ ]:
mean = t3.mean()
max = t3.max()
median  = np.median(t3)
std = np.std(t3)
var = np.var(t3)

In [ ]:
print (median)

8.0


In [ ]:
print (mean)

8.0


In [ ]:
print (max)

10


In [ ]:
print (std)

0.9428090415820634


In [ ]:
print (var)

0.8888888888888888


In [ ]:
# Trigonometric functions
# sin(x)
# cos(x)
# Tan(x)- sin(x)/cos(x)
# cosec - 1/sin(x)
# sec - 1/ cos(x)
# cot - 1/ tan(x)
angles = np.array([0,15,30,45,60,75,90])

In [ ]:
result = np.sin(np.radians(angles))
result = np.cos(np.radians(angles))
result = np.tan(np.radians(angles))

In [ ]:
print (result)
print (result ,1)
print (result ,2)

[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16] 1
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16] 2


In [ ]:
arr = np.array([1,2,3,4,5,6])
#Reshape the array
reshapedarr = arr.reshape(3,2)
print (reshapedarr)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#convert / Flatten any n dim array
flattenedarr = arr.flatten()
print (flattenedarr)

[1 2 3 4 5 6]


In [ ]:
# Stacking the data
# Vertical staking
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])
arr3 = np.vstack((arr1,arr2))
print(f" The shape of arr3 is{arr3.shape}")

 The shape of arr3 is(2, 4)


In [ ]:
#Horizontal stacking
arr4 = np.hstack((arr1,arr2))
print(f" The shape of arr4 is {arr4.shape}")
print (arr4)

 The shape of arr4 is (8,)
[ 1  2  3  4 10 20 30 40]


In [ ]:
#Filtering the data
arr = np.array ([10,20,30,40,50,60,70,80])
farr = arr[arr> 50]
farr1 = arr[arr<50]
farr2 = arr[arr>=20]
print (farr)
print (farr1)
print (farr2)

[60 70 80]
[10 20 30 40]
[20 30 40 50 60 70 80]
